#!/usr/bin/env bash

function bootstrap {
  local shome="${_postgresql_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  pkg ensure databases/postgresql94
}

bootstrap
